import numpy as np

# ==========================================
# SYSTEM PARAMETERS (PHASS / CCIoT Domain)
# ==========================================

# N is the length of the vector/polynomial (power of 2 is standard in lattice crypto)
# For a real system, this might be 512 or 1024. We use 256 for efficient simulation.
N = 256 

# Q is the modulus (a prime number). All math operations wrap around this number.
# 3329 is a standard modulus used in modern lattice-based cryptography (like Kyber).
Q = 3329 

# ==========================================
# MATHEMATICAL HELPER FUNCTIONS
# ==========================================

def generate_random_poly(size=N, modulus=Q):
    """
    Generates a random polynomial (vector) with coefficients between 0 and Q-1.
    This is used for generating keys, secrets (s), and random commitments (y).
    """
    return np.random.randint(0, modulus, size)

def generate_short_poly(size=N, bound=5):
    """
    Generates a 'short' polynomial with small coefficients (e.g., -bound to +bound).
    In lattice cryptography, the 'noise' or 'secret' must be small to be secure.
    """
    return np.random.randint(-bound, bound + 1, size)

def hadamard_product(poly1, poly2, modulus=Q):
    """
    The core of PH-SIS: Pointwise/Element-wise multiplication.
    poly1 ⊛ poly2 mod Q
    """
    return np.mod(np.multiply(poly1, poly2), modulus)

def poly_add(poly1, poly2, modulus=Q):
    """Adds two polynomials coefficient-wise mod Q."""
    return np.mod(np.add(poly1, poly2), modulus)

def poly_sub(poly1, poly2, modulus=Q):
    """Subtracts poly2 from poly1 coefficient-wise mod Q."""
    return np.mod(np.subtract(poly1, poly2), modulus)

# The global public parameter p(x) generated by the CA
# (We generate it once here so all modules can import the exact same 'p')
GLOBAL_P = generate_random_poly()